id: 87e9e394-6bae-4ac8-b724-8ba07d37cca7
name: dedupe_OverallStatus
description: null
isGlobal: false
testSuiteId: test-suite-1765783670576
parameters:
- status
content: |-
  And click "Overall Status"
  And click on the 2nd "Overall Status"
  And click "{status}"
  And click "Remark"
  And enter "add-remark"
  And click "submit"
createdAt: '2025-12-16T08:46:31.925023800Z'
updatedAt: '2025-12-16T08:46:31.925023800Z'
